# Generated by Django 2.2 on 2019-11-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191103_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='191103082700', editable=False, max_length=140, unique=True),
        ),
    ]
