# Generated by Django 2.2 on 2019-11-03 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20191103_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='191103092701', max_length=140),
        ),
    ]
